version: 2

project_name: protopeek

builds:
  - id: protopeek
    binary: protopeek
    main: ./cmd/protopeek
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version=v{{ .Version }}

archives:
  - id: protopeek
    builds:
      - protopeek
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .Binary }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}osx{{ else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}x86_32{{ else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    files:
      - LICENSE

checksum:
  name_template: checksums.txt

release:
  prerelease: true
  make_latest: false
  extra_files:
    - glob: ./install.sh

changelog:
  disable: true
